<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="roadrunner">
<xacro:property name="wheel_radius" value="0.03" />
<xacro:property name="wheel_separation" value="0.12" />
<xacro:property name="show_wheels" value="false" />
<xacro:macro name="ball_wheel" params="origin name">
	<link name="${name}_link">
		<collision>
			<geometry>
				<sphere radius="0.005"/>
			</geometry>
		</collision>
			<inertial>
				<mass value="0.01"/>
				<inertia
					ixx="0.000001" ixy="0.0" ixz="0.0"
					iyy="0.000001" iyz="0.0"
					izz="0.000001" />
			</inertial>
		<xacro:if value="${show_wheels}">
			<visual>
				<geometry>
					<sphere radius="0.005"/>
				</geometry>
			</visual>
		</xacro:if>
	</link>
		<gazebo reference="${name}_link">
			<material>Gazebo/Orange</material>
			<mu1 value="0.1"/>
			<mu2 value="0.1"/>
		</gazebo>
		<joint name="${name}_joint" type="fixed">
			<origin xyz="${origin}"/>
			<parent link="body_link"/>
			<child link="${name}_link"/>
		</joint>
</xacro:macro>
	<xacro:macro name="wheel" params="xyz rpy name">
		<link name="${name}_link">
			<collision name="collision">
				<geometry>
					<cylinder radius="${wheel_radius}" length="0.01"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="0.01"/>
				<inertia
					ixx="0.000001" ixy="0.0" ixz="0.0"
					iyy="0.000001" iyz="0.0"
					izz="0.000001" />
			</inertial>
		<xacro:if value="${show_wheels}">
			<visual>
				<geometry>
					<cylinder radius="${wheel_radius}" length="0.01"/>
				</geometry>
			</visual>
		</xacro:if>
		</link>
		<gazebo reference="${name}_link">
			<material>Gazebo/Orange</material>
			<mu1 value="0.8"/>
			<mu2 value="0.8"/>
		</gazebo>
		<joint name="${name}_joint" type="continuous">
			<origin xyz="${xyz}" rpy="${rpy}"/>
			<parent link="body_link"/>
			<child link="${name}_link"/>
			<axis xyz="0 0 -1"/>
		</joint>
	</xacro:macro>

	<link name="base_link">
			<inertial>
				<mass value="0.01"/>
				<inertia
					ixx="0.000001" ixy="0.0" ixz="0.0"
					iyy="0.000001" iyz="0.0"
					izz="0.000001" />
			</inertial>
	</link>
		<joint name="base_joint" type="fixed">
			<origin xyz="0 0 0.025"/>
			<parent link="base_link"/>
			<child link="body_link"/>
		</joint>
	<link name="body_link">
		<collision>
			<origin xyz="0 0 0"/>
			<geometry>
				<box size="0.12 0.07 0.05"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 -0.005 0.02" rpy="1.571 0 1.571"/>
				<geometry>
					<mesh filename="package://kamagami/meshes/kamagami.dae" scale="0.001 0.001 0.001"/>
				</geometry>
		</visual>
		<inertial>
			<origin xyz="0 0 0"/>
			<mass value="0.105"/>
			<inertia
				ixx="0.00006475" ixy="0.0" ixz="0.0"
				iyy="0.000168875" iyz="0.0"
				izz="0.00147875"/>
		</inertial>
	</link>
	<gazebo reference="body_link">
		<material>Gazebo/Black</material>
	</gazebo>
	<xacro:ball_wheel origin="-0.05 0 -0.025" name="ball"/>
	<xacro:wheel name="left_wheel" xyz="0.05 ${wheel_separation/2.0} 0" 
		rpy="1.5708 0 0"/>
	<xacro:wheel name="right_wheel" xyz="0.05 -${wheel_separation/2.0} 0" 
		rpy="1.5708 0 0"/>

	<link name="raspicam_link">
		<visual>
			<geometry>
				<box size="0.01 0.02 0.02"/>
			</geometry>
		</visual>
	</link>
	<joint name="raspicam_joint" type="fixed">
		<parent link="body_link"/>
		<child link="raspicam_link"/>
		<origin xyz="0.05 0 0.02" rpy="0 0 0"/>
	</joint>
	<gazebo reference="raspicam_link">
		<material>Gazebo/Grey</material>
		<sensor type="camera" name="raspicam">
			<!--			<pose>0.089 -0.01 0.236 0 0.436 0</pose> -->
			<update_rate>6.0</update_rate>
			<camera name="raspicam">
				<horizontal_fov>1.0123</horizontal_fov>
				<image>
					<width>640</width>
					<height>480</height>
					<format>B8G8R8</format>
				</image>
				<clip>
					<near>0.02</near>
					<far>300</far>
				</clip>
				<noise>
					<type>gaussian</type>
					<mean>0.0</mean>
					<stddev>0.007</stddev>
				</noise>
			</camera>
			<plugin name="camera_controller" filename="libgazebo_ros_camera.so">
				<alwaysOn>true</alwaysOn>
				<updateRate>0.0</updateRate>
				<cameraName>raspicam</cameraName>
				<imageTopicName>image</imageTopicName>
				<cameraInfoTopicName>camera_info</cameraInfoTopicName>
				<frameName>raspicam_link</frameName>
				<hackBaseline>0.1</hackBaseline>
				<distortionK1>.0</distortionK1>
				<distortionK2>0.0</distortionK2>
				<distortionK3>0.0</distortionK3>
				<distortionT1>0.0</distortionT1>
				<distortionT2>0.0</distortionT2>
			</plugin>
		</sensor>
	</gazebo>
	<gazebo>
	  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
	    <alwaysOn>true</alwaysOn>
	    <legacyMode>false</legacyMode>
	    <publishWheelTF>false</publishWheelTF>
	    <publishTf>true</publishTf>
	    <publishWheelJointState>false</publishWheelJointState>
	    <leftJoint>left_wheel_joint</leftJoint>
	    <rightJoint>right_wheel_joint</rightJoint>
	    <wheelAcceleration>0</wheelAcceleration>
	    <wheelTorque>5</wheelTorque>
	    <torque>1</torque>
	    <commandTopic>cmd_vel</commandTopic>
	    <odometryTopic>odom</odometryTopic>
	    <odometrySource>encoder</odometrySource>
	    <odometryFrame>odom</odometryFrame>
	    <rosDebugLevel>none</rosDebugLevel>
	    <robotBaseFrame>base_link</robotBaseFrame>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2.0}</wheelDiameter>
			<updateRate>100</updateRate>
	  </plugin>
	</gazebo>
  <joint name="laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0.04" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="laser_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="laser_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
    <gazebo reference="laser_link">
        <sensor name="laser" type="ray">
        <pose>0 0 0 0 0 0</pose>
          <ray>
            <scan>
              <horizontal>
                <!-- The URG-04LX-UG01  has  683 steps with 0.35139 Degree resolution -->
                <resolution>1</resolution>
                <max_angle>2.0944</max_angle> <!-- 120 Degree -->
                <min_angle>-2.0944</min_angle> <!-- -120 Degree -->
                <samples>683</samples>
              </horizontal>
            </scan>
            <range>
              <min>0.08</min>
              <max>10</max>
              <resolution>0.01</resolution>
            </range>
          </ray>
          
          <plugin name="laser" filename="libgazebo_ros_laser.so" >
            <robotNamespace></robotNamespace>
            <topicName>scan</topicName>
            <frameName>laser_link</frameName>
          </plugin>
          <!--
          <plugin name="laser" filename="libRayPlugin.so" />
          -->
          
          <always_on>1</always_on>
          <update_rate>30</update_rate>
          <visualize>true</visualize>        
        </sensor>
    </gazebo>

</robot>
