global_frame: map
robot_base_frame: base_link

footprint: [[-0.05, -0.05], [-0.05, 0.05], [0.05, 0.05], [0.05, -0.05]]
footprint_padding: 0.01

transform_tolerance: 0.5

resolution: 0.1


obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
  map_topic: /map
  subscribe_to_updates: true

inflation:
  inflation_radius: 1.0

inflation_local:
  enabled: true
  cost_scaling_factor: 5
  inflation_radius: 1.0

obstacles_laser:
  enabled: true
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}


